##
##  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
## ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
## ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
## ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
## ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
## ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
## A cross-platform, OpenGL terminal emulator.
## https://alacritty.org

import = [
"~/.config/alacritty/catppuccin-mocha.toml",
]

shell = { program = "/usr/local/bin/fish", args = ["-l"] }
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 0.9
blur = true
resize_increments = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 104
lines = 36

[window.padding]
x = 10
y = 5

[font]
size = 13.0

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Off"

[selection]
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Right"
action = "Paste"


# █▀ █░█ █▀█ █▀█ ▀█▀ █▀▀ █░█ ▀█▀ █▀
# ▄█ █▀█ █▄█ █▀▄ ░█░ █▄▄ █▄█ ░█░ ▄█


[[keyboard.bindings]]
# split tmux window vertically
key = "E"
mods = "Command"
chars = "\u0001\""

[[keyboard.bindings]]
# split tmux window horizontally
key = "E"
mods = "Command|Shift"
chars = "\u0001%"

[[keyboard.bindings]]
# start tmux search mode
key = "F"
mods = "Command"
chars = "\u0001\u005b\u002f"

[[keyboard.bindings]]
# open sesh popup
key = "K"
mods = "Command"
chars = "\u0001\u004b"

[[keyboard.bindings]]
# create new tmux window
key = "N"
mods = "Command"
chars = "\u0001c"

[[keyboard.bindings]]
# create new alacritty window
key = "N"
mods = "Command|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
# rename session name
key = "R"
mods = "Command"
chars = "\u0001$"

[[keyboard.bindings]]
# refresh tmux configuration
key = "R"
mods = "Command|Shift"
chars = "\u0001r"

[[keyboard.bindings]]
# install new tmux plugins
key = "I"
mods = "Command|Shift"
chars = "\u0001\u0049"

[[keyboard.bindings]]
# show tmux session window
key = "S"
mods = "Command"
chars = "\u0001s"

[[keyboard.bindings]]
# create new tmux session
key = "S"
mods = "Command|Shift"
chars = "\u0001\u0053"

[[keyboard.bindings]]
# kill the current pane
key = "W"
mods = "Command"
chars = "\u0001x"

[[keyboard.bindings]]
# kill the current tmux window
key = "W"
mods = "Command|Shift"
chars = "\u0001&"

[[keyboard.bindings]]
# switch to next tmux window
key = "Tab"
mods = "Control"
chars = "\u0001n"

[[keyboard.bindings]]
# switch to previous tmux window
key = "Tab"
mods = "Control|Shift"
chars = "\u0001p"

[[keyboard.bindings]]
# enter the tmux command prompt
key = "."
mods = "Command"
chars = "\u0001:"

[[keyboard.bindings]]
# rename the current tmux window
key = ","
mods = "Command"
chars = "\u0001,"

[[keyboard.bindings]]
# select tmux window 0
key = "0"
mods = "Command"
chars = "\u00010"

[[keyboard.bindings]]
# select tmux window 1
key = "1"
mods = "Command"
chars = "\u00011"

[[keyboard.bindings]]
# select tmux window 2
key = "2"
mods = "Command"
chars = "\u00012"

[[keyboard.bindings]]
# select tmux window 3
key = "3"
mods = "Command"
chars = "\u00013"

[[keyboard.bindings]]
# select tmux window 4
key = "4"
mods = "Command"
chars = "\u00014"

[[keyboard.bindings]]
# select tmux window 5
key = "5"
mods = "Command"
chars = "\u00015"

[[keyboard.bindings]]
# select tmux window 6
key = "6"
mods = "Command"
chars = "\u00016"

[[keyboard.bindings]]
# select tmux window 7
key = "7"
mods = "Command"
chars = "\u00017"

[[keyboard.bindings]]
# select tmux window 8
key = "8"
mods = "Command"
chars = "\u00018"

[[keyboard.bindings]]
# select tmux window 9
key = "9"
mods = "Command"
chars = "\u00019"

[[keyboard.bindings]]
# switch to left pane
key = "H"
mods = "Command|Shift"
chars = "\u0001h"

[[keyboard.bindings]]
# switch to lower pane
key = "J"
mods = "Command|Shift"
chars = "\u0001j"

[[keyboard.bindings]]
# switch to upper pane
key = "K"
mods = "Command|Shift"
chars = "\u0001k"

[[keyboard.bindings]]
# switch to right pane
key = "L"
mods = "Command|Shift"
chars = "\u0001l"
