[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.repos]
"~/.dotfiles" = { url = "git@github.com:kyrarae/dotfiles.git", ref = "main" }

[dotfiles]
"~/.config/mise/config.toml" = "mise.toml"
"~/.config/bat" = "bat"
"~/.config/btop" = "btop"
"~/.config/emacs" = "emacs"
"~/.config/fish" = "fish"
"~/.config/gh" = "gh"
"~/.config/ghostty" = "ghostty"
"~/.config/git" = "git"
"~/.config/helix" = "helix"
"~/.config/kanata" = "kanata"
"~/.config/lazygit" = "lazygit"
"~/.config/starship.toml" = "starship/starship.toml"
"~/.config/tmux" = "tmux"
"~/.config/tmux-snaglord" = "tmux-snaglord"
"~/.config/yazi" = "yazi"
"~/.config/zed" = "zed"

[tools]
bat = "latest"
"github:paulilaaso/bit" = "latest"
c3 = "latest"
"github:pherrymason/c3-lsp" = { version = "latest", os = ["macos/arm64"], bin_path = "server/bin/release" }
"github:clangd/clangd" = "latest"
"github:so-fancy/diff-so-fancy" = "latest"
eza = "latest"
fd = { version = "latest", os = ["macos/arm64"] }
fzf = "latest"
gh = "latest"
gum = "latest"
helix = "latest"
just = "latest"
jq = "latest"
lazygit = "latest"
node = "lts"
odin = "latest"
"github:DanielGavin/ols" = { version = "latest", rename_exe = { "ols-*" = "ols", "odinfmt-*" = "odinfmt" }}
"github:SimonBure/presse" = "latest"
python = ["3.11", "3.13"]
"github:cesarferreira/rip" = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
"github:raine/tmux-snaglord" = "latest"
vlang = "latest"
"github:vlang/v-analyzer" = "latest"
xcodegen = "latest"
yazi = "latest"
zoxide = "latest"
