#
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# A Rust-powered, customizable cross-shell prompt.
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
$username\
$hostname\
$directory\
$docker_context\
$package\
$c\
${custom.cpp}\
$nodejs\
$rust\
$python\
$golang\
$lua\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$git_commit\
\n\
$character
"""

right_format = """
$status\
$cmd_duration
"""

palette = "catppuccin_mocha"

# System specific modules

[directory]
style = "pink"
format = "in [ $path ]($style)"
read_only = " 󰌾"
truncation_length = 5
truncation_symbol = "…/"

[cmd_duration]
min_time = 500

[username]
style_user = 'lavender'
style_root = 'red'
disabled = false
format = "[$user]($style)"
show_always = true

[hostname]
style = "lavender"
disabled = false
format = "[@$hostname$ssh_symbol]($style) "
ssh_only = false
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[status]
symbol = '✗ '
success_symbol = '[✓](fg:green)'
not_executable_symbol = '! '
not_found_symbol = '? '
sigint_symbol = '✗ '
signal_symbol = '󱐋 '
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false

# VCS indicator modules

[fossil_branch]
symbol = " "

[git_branch]
style = "bold blue"
symbol = " "

[git_commit]
style = "bold green"
tag_symbol = " "
tag_disabled = false

[git_status]
style = "bold red"
ahead = "↑"
behind = "↓"
conflicted = "!"
deleted = "×"
diverged = "↕"
modified = "~"
renamed = "»"
untracked = "+"
staged = "●"
stashed = "ﮅ "

[hg_branch]
symbol = " "

# Context indicator modules

[aws]
style = "bold yellow"
symbol = " "

[docker_context]
style = "bold blue"
symbol = " "

[gcloud]
style = "bold blue"
symbol = " "

# Language specific modules

[buf]
symbol = " "

[bun]
symbol = " "

[c]
style = "bold blue"
format = " [$symbol($version(-$name) )]($style)"
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
style = "bold blue"
format = " [$symbol($version )]($style)"
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
style = "bold blue"
format = ' [$symbol($version )]($style)'
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
style = "bold green"
format = " [$symbol($version )]($style)"
symbol = " "

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
style = "bold yellow"
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
style = "bold red"
format = " [$symbol($version )]($style)"
symbol = " "

[rust]
style = "bold red"
format = " [$symbol($version )]($style)"
symbol = " "

[scala]
symbol = " "

[swift]
style = "bold peach"
format = " [$symbol($version )]($style)"
symbol = " "

[zig]
symbol = " "

# OS specific indicators

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

# Package version module

[package]
style = "bold maroon"
symbol = "󰏗 "

# Custom command modules

[custom.cpp]
command = "gcc -dumpversion"
symbol = ""
extensions = ["cpp"]
style = "bold yellow"
format = " [$symbol v$output]($style) "

[custom.giturl]
style = "bold maroon"
description = "Display symbol for remote Git server"
command = """
IFS="/"
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
read -ra GIT_HOST <<< "$GIT_REMOTE"
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" localhost"
fi
printf "$GIT_REMOTE_SYMBOL${GIT_HOST[2]:-$GIT_HOST}"
IFS=" "
"""
shell = ["bash","--norc","--noprofile"]
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "\nat [$output]($style) "

# Theme palettes

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

