[tools]
bat = "latest"
"github:paulilaaso/bit" = "latest"
c3 = "latest"
"github:clangd/clangd" = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
gum = "latest"
helix = "latest"
just = "latest"
jq = "latest"
lazygit = "latest"
node = "lts"
odin = "latest"
"github:DanielGavin/ols" = { version = "latest", rename_exe = { "ols-*" = "ols", "odinfmt-*" = "odinfmt" }}
"github:SimonBure/presse" = "latest"
python = ["3.11", "3.13"]
"github:cesarferreira/rip" = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
"github:raine/tmux-snaglord" = "latest"
vlang = "latest"
"github:vlang/v-analyzer" = "latest"
xcodegen = "latest"
yazi = "latest"
zoxide = "latest"
